import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import "./index.css";
export default function App() {
    return (_jsxs("div", { style: { padding: "2rem", maxWidth: "900px", margin: "0 auto" }, children: [_jsxs("header", { style: { marginBottom: "3rem" }, children: [_jsx("h1", { style: { fontSize: "2.5rem", fontWeight: "bold" }, children: "Your Name" }), _jsx("p", { style: { color: "#9ca3af" }, children: "Cybersecurity Analyst | QA | Pentester" })] }), _jsxs("section", { style: { marginBottom: "2rem" }, children: [_jsx("h2", { style: { fontSize: "1.5rem", fontWeight: "600" }, children: "About Me" }), _jsx("p", { style: { color: "#d1d5db" }, children: "Passionate cybersecurity professional with experience in pentesting, vulnerability assessments, and automation testing." })] }), _jsxs("section", { style: { marginBottom: "2rem" }, children: [_jsx("h2", { style: { fontSize: "1.5rem", fontWeight: "600" }, children: "Skills" }), _jsx("div", { style: { display: "flex", flexWrap: "wrap", gap: "0.5rem" }, children: ["PenTesting", "Network Security", "OWASP", "Burp Suite", "Python", "Automation Testing"].map((skill) => (_jsx("span", { style: {
                                backgroundColor: "#1f2937",
                                padding: "0.3rem 0.8rem",
                                borderRadius: "9999px",
                                fontSize: "0.875rem",
                            }, children: skill }, skill))) })] }), _jsxs("section", { style: { marginBottom: "2rem" }, children: [_jsx("h2", { style: { fontSize: "1.5rem", fontWeight: "600" }, children: "Projects" }), _jsx("div", { style: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: "1rem" }, children: _jsxs("div", { style: { backgroundColor: "#1f2937", padding: "1rem", borderRadius: "12px" }, children: [_jsx("h3", { style: { fontSize: "1.25rem", fontWeight: "600" }, children: "Pentest Report" }), _jsx("p", { style: { color: "#9ca3af", marginTop: "0.5rem" }, children: "Full-cycle penetration test including recon, exploitation, and reporting." })] }) })] }), _jsxs("section", { children: [_jsx("h2", { style: { fontSize: "1.5rem", fontWeight: "600" }, children: "Contact" }), _jsx("p", { style: { color: "#d1d5db" }, children: "Email: your.email@example.com" }), _jsxs("p", { style: { color: "#d1d5db" }, children: ["GitHub: ", _jsx("a", { href: "https://github.com/xx-xx", target: "_blank", style: { color: "#2563eb" }, children: "github.com/xx-xx" })] })] })] }));
}
